---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: onsdigital/dp-concourse-tools-git

inputs:
  - name: build
  - name: artifacts
  - name: dp-dd-search-indexer

outputs:
  - name: deployment

run:
  path: dp-dd-search-indexer/ci/scripts/deployment-bundle.sh
